### ISSUE TITLE
issue with recent changes in brukerimage : regression on windows 32 bits

### ISSUE THREAD

**Issue by kif** [kif/fabio#59]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\kieffer\workspace\fabio\build\lib.win-amd64-3.4\fabio\test\testbrukerimage.py", line 142, in test_linea
r
    obj.write(self.filename)
  File "C:\Users\kieffer\workspace\fabio\build\lib.win-amd64-3.4\fabio\brukerimage.py", line 311, in write
    data[reset] = limit
OverflowError: Python int too large to convert to C long

**Comment by kif** [comment]
looks like fixed
